const WORD_SETS = [
  {
    id: "football",
    label: "Fútbol",
    icon: "⚽",
    description: "Para ese colega que mete fútbol hasta en los cumpleaños.",
    words: [
      "Lionel Messi",
      "Cristiano Ronaldo",
      "Neymar",
      "Kylian Mbappé",
      "Erling Haaland",
      "Vinícius Jr",
      "Luka Modrić",
      "Toni Kroos",
      "Karim Benzema",
      "Robert Lewandowski",
      "Kevin De Bruyne",
      "Mohamed Salah",
      "Harry Kane",
      "Sergio Ramos",
      "Iker Casillas",
      "Andrés Iniesta",
      "Xavi Hernández",
      "Wayne Rooney",
      "Didier Drogba",
      "Zlatan Ibrahimović",
      "Luis Suárez",
      "Gareth Bale",
      "Ronaldinho",
      "Ronaldo Nazário",
      "Zinedine Zidane",
      "Thierry Henry",
      "Paolo Maldini",
      "Andrea Pirlo",
      "Manuel Neuer",
      "Gianluigi Buffon",
      "Phil Foden",
      "Pedri",
      "Rodri",
      "Sadio Mané",
      "Antoine Griezmann",
      "Marco Reus",
      "Paul Pogba",
      "Edinson Cavani",
      "Angel Di María",
      "Jude Bellingham",
      "João Félix",
      "Mateo Kovacic",
      "Declan Rice",
      "Riyad Mahrez",
      "Sergio Agüero",
      "Mesut Özil",
      "Frank Lampard",
      "Steven Gerrard",
      "Kaká"
    ]
  },
  {
    id: "celebrities",
    label: "Famosos",
    icon: "⭐",
    description: "Gente que conoces aunque no quieras.",
    words: [
      "Taylor Swift",
      "Rihanna",
      "Beyoncé",
      "Shakira",
      "Dua Lipa",
      "Lady Gaga",
      "Billie Eilish",
      "Ariana Grande",
      "Jennifer Lopez",
      "Bad Bunny",
      "Karol G",
      "Elon Musk",
      "Mark Zuckerberg",
      "Jeff Bezos",
      "MrBeast",
      "PewDiePie",
      "Kim Kardashian",
      "Kanye West",
      "Selena Gomez",
      "Justin Bieber",
      "Ed Sheeran",
      "Keanu Reeves",
      "Ryan Reynolds",
      "Dwayne Johnson",
      "Tom Cruise",
      "Robert Downey Jr.",
      "Scarlett Johansson",
      "Emma Watson",
      "Brad Pitt",
      "Angelina Jolie",
      "Zendaya",
      "Timothée Chalamet",
      "Pedro Pascal",
      "Henry Cavill",
      "Jason Momoa",
      "Chris Hemsworth",
      "Chris Evans",
      "Morgan Freeman",
      "Samuel L. Jackson",
      "Will Smith",
      "Megan Fox",
      "Miley Cyrus",
      "Snoop Dogg",
      "Gordon Ramsay",
      "Lionel Messi",
      "Cristiano Ronaldo"
    ]
  },
  {
    id: "animals",
    label: "Animales",
    icon: "🐾",
    description: "Modo fácil. Perfecto para impostores vagos.",
    words: [
      "Perro",
      "Gato",
      "Caballo",
      "Vaca",
      "Oveja",
      "Mono",
      "Gorila",
      "Chimpancé",
      "Panda",
      "Oso polar",
      "León",
      "Tigre",
      "Pantera",
      "Cebra",
      "Jirafa",
      "Elefante",
      "Rinoceronte",
      "Hipopótamo",
      "Canguro",
      "Delfín",
      "Ballena",
      "Tiburón",
      "Pez espada",
      "Pez payaso",
      "Pulpo",
      "Calamar",
      "Pingüino",
      "Águila",
      "Halcón",
      "Búho",
      "Cocodrilo",
      "Serpiente",
      "Lagarto",
      "Camaleón",
      "Tortuga",
      "Conejo",
      "Hamster",
      "Zorro",
      "Lobo",
      "Murciélago",
      "Camello",
      "Avestruz",
      "Gaviota",
      "Mapache",
      "Castor"
    ]
  },
  {
    id: "food",
    label: "Comida",
    icon: "🍕",
    description: "Ideal para jugar con hambre. O para provocarla.",
    words: [
      "Pizza",
      "Hamburguesa",
      "Hot Dog",
      "Croquetas",
      "Paella",
      "Sushi",
      "Tacos",
      "Burrito",
      "Nachos",
      "Ramen",
      "Kebab",
      "Falafel",
      "Tortilla de patatas",
      "Huevos fritos",
      "Patatas fritas",
      "Nuggets",
      "Sándwich mixto",
      "Bocadillo de jamón",
      "Queso",
      "Yogur",
      "Ensalada",
      "Chocolate",
      "Helado",
      "Galletas",
      "Brownie",
      "Bizcocho",
      "Plátano",
      "Sandía",
      "Manzana",
      "Melón",
      "Café",
      "Té",
      "Coca-Cola",
      "Fanta",
      "Donut",
      "Churros",
      "Empanada",
      "Arepa",
      "Pasta",
      "Lasagna"
    ]
  },
  {
    id: "videogames",
    label: "Videojuegos",
    icon: "🎮",
    description: "Para gamers, ex-gamers y gente que finge saber.",
    words: [
      "Mario",
      "Luigi",
      "Peach",
      "Bowser",
      "Yoshi",
      "Pikachu",
      "Charizard",
      "Link",
      "Zelda",
      "Ganondorf",
      "Sonic",
      "Tails",
      "Knuckles",
      "Kirby",
      "Samus Aran",
      "Master Chief",
      "Kratos",
      "Atreus",
      "Lara Croft",
      "Nathan Drake",
      "Geralt de Rivia",
      "Ciri",
      "Gordon Freeman",
      "Agent 47",
      "Cloud Strife",
      "Sephiroth",
      "Marcus Fenix",
      "Trevor Philips",
      "CJ (GTA)",
      "Minecraft Steve",
      "Alex (Minecraft)",
      "Pac-Man",
      "Donkey Kong",
      "Ryu",
      "Chun-Li",
      "Sub-Zero",
      "Scorpion",
      "Sheik",
      "Ezio Auditore",
      "Ellie",
      "Joel",
      "Cuphead",
      "Sans (Undertale)"
    ]
  },
  {
    id: "objects",
    label: "Objetos",
    icon: "🎲",
    description: "Cosas random que reconocerías incluso medio dormido.",
    words: [
      "Silla",
      "Mesa",
      "Cuchara",
      "Tenedor",
      "Cuchillo",
      "Taza",
      "Botella",
      "Móvil",
      "Cargador",
      "Auriculares",
      "Televisión",
      "Mando a distancia",
      "Ordenador portátil",
      "Teclado",
      "Ratón",
      "Libro",
      "Lámpara",
      "Almohada",
      "Manta",
      "Colchón",
      "Cepillo de dientes",
      "Toalla",
      "Reloj",
      "Llave",
      "Cartera",
      "Gafas",
      "Bolígrafo",
      "Cuaderno",
      "Perfume",
      "Bolsa",
      "Mochila",
      "Ventilador",
      "Plancha",
      "Botiquín",
      "Espejo",
      "Velas",
      "Maceta",
      "Jarrón"
    ]
  },
  {
    id: "custom",
    icon: "📝",
    label: "Palabras personalizadas",
    description: "Escribid vuestras propias palabras. Chistes internos bienvenidos."
  }
]

function pickRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

const WordSets = {
  getAll: () => WORD_SETS,
  getWordFromSet: (set) => WordSets.getRandomWordFromWords(set.words),
  getRandomWordFromWords: (words) => pickRandom(words),
  getSet: (setId) => WORD_SETS.find((s) => s.id === setId),
}

export default WordSets